### ISSUE TITLE
SNOW-901157: Session.builder.getOrCreate does not take into consideration if the authentication token has expired

### ISSUE THREAD

**Issue by sfc-gh-mrojas** [snowflakedb/snowpark-python#1022]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

2. What operating system and processor architecture are you using?

 macOS-13.5-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

4. What did you do?

I have a program that is using Session.builder.configs(config_dict).getOrCreate() the program is running for a few hours, after 4hrs the authentication token gets revoked but context() and getOrCreate() return the same session and that session will fail with an error message about AuthenticationToken

5. What did you expect to see?

   It should have logged that the authentication token is expired and try to do a create

**Comment by sfc-gh-aalam** [comment]
Is the function doing put/get operation for 4hrs?

**Comment by sfc-gh-mrojas** [comment]
The program is orchestrating tasks. And the orchestrator is "alive" for more that 4 hours. So at some point the context will return an instance which has an expired lifespan

**Comment by sfc-gh-mkeller** [comment]
@sfc-gh-mrojas What kind of authentication are you using? Is it `externalbrowser`?

**Comment by sfc-gh-mrojas** [comment]
It happens with different authentication methods but this last case is user
/password
