### ISSUE TITLE
SNOW-952961: Wrong documentation for daydiff function

### ISSUE THREAD

**Issue by julienripoche** [snowflakedb/snowpark-python#1112]
https://github.com/snowflakedb/snowpark-python/blob/44a8e175baed8d3432d563de3d845531f35e04e7/src/snowflake/snowpark/functions.py#L3819

The documentation of the daydiff function states that the result is the difference between col2 and col1.

"""Calculates the difference between two dates, or timestamp columns based in days.
The result will reflect the difference between col2 - col1
"""

Whereas it actually is the difference between col1 and col2.

"""
Example::
    >>> from snowflake.snowpark.functions import daydiff, to_date
    >>> df = session.createDataFrame([("2015-04-08", "2015-05-10")], ["d1", "d2"])
    >>> res = df.select(daydiff(to_date(df.d2), to_date(df.d1)).alias("diff")).show()
    ----------
    |"DIFF"  |
    ----------
    |32      |
    ----------
    <BLANKLINE>
"""

I understand that this is the intended behaviour.

https://github.com/snowflakedb/snowpark-python/issues/730

So I ask that the documentation is updated in order to make the actual behaviour clear.

"""Calculates the difference between two dates, or timestamp columns based in days.
The result will reflect the difference between col1 - col2

Example::
    >>> from snowflake.snowpark.functions import daydiff, to_date
    >>> df = session.createDataFrame([("2015-04-08", "2015-05-10")], ["d1", "d2"])
    >>> res = df.select(daydiff(to_date(df.d2), to_date(df.d1)).alias("diff")).show()
    ----------
    |"DIFF"  |
    ----------
    |32      |
    ----------
    <BLANKLINE>
"""

**Comment by sfc-gh-aalam** [comment]
Thanks for pointing this out @julienripoche
