### ISSUE TITLE
SNOW-1062439: Automatically closing sessions and connections using Python `with` leads to errors when deploying to stored procedures

### ISSUE THREAD

**Issue by zaramzamzam** [snowflakedb/snowpark-python#1259]
When creating a session I am using the Python `with` statement in order to automatically close the connection and remove the session.

## What is the current behavior?

Currently using the `with` statement to automatically close connections when running in Stored Procedures or Snowflake Streamlit apps throws an error due to closing the connection not being allowed in stored procedures.

https://github.com/snowflakedb/snowpark-python/blob/2d889940d86af9c4903f3b5ae4a7c6ae5a608ed3/src/snowflake/snowpark/session.py#L492-L495

This leads to the code having to be different when running locally or in stored procedures.

## What is the desired behavior?

Ideally I would like the same Python code to run locally as well as in stored procedures or Streamlit apps.

## How would this improve `snowflake-snowpark-python`?

This would make it easier to develop locally and then moving deployments to Snowflake, for example in the form of Streamlit Apps.

## Possible Solution

Instead of throwing an error a warning could be logged and when detecting that code is running inside a stored procedure the session is not closed, ignoring the `with` functionality.

**Comment by zaramzamzam** [comment]
If this is seen as an improvement I would be happy to contribute to this issue via a PR.

**Comment by sfc-gh-stan** [comment]
Thanks for opening this. The proposed change makes sense to me, please open a PR and request review from @sfc-gh-yixie 🙂

**Comment by zaramzamzam** [comment]
Hi @sfc-gh-stan I added a PR, but I am unable to select a specific reviewer myself.
