### ISSUE TITLE
SNOW-1065294: Null value in integer column raises exception when executing .to_pandas() in version ^1.12 for mock connections

### ISSUE THREAD

**Issue by shanefrieskh** [snowflakedb/snowpark-python#1264]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

`Python 3.11.2`

2. What are the Snowpark Python and Pandas versions in the environment?

```
pandas==2.1.4
snowflake-snowpark-python==1.12.1
```

3. What did you do?

```python
session = Session.builder.config('local_testing', True).create()
df = session.create_dataframe(
    data=[
        [1],
        [None],
    ],
    schema=["C1"]
)
print(df.to_pandas())
```

returns:
`TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

Similar to #1232 but in mock connection handling

4. What did you expect to see?

```
    C1
0  1.0
1  NaN
```

**Comment by sfc-gh-aling** [comment]
thanks @shanefrieskh for reaching out. we will take a look at this issue

**Comment by sfc-gh-jfreeberg** [comment]
@shanefrieskh -- Can you re-try with v1.14.0? It should be fixed.

**Comment by shanefrieskh** [comment]
@sfc-gh-jfreeberg confirmed it has been working since 1.14. Thank you for the quick fix
