### ISSUE TITLE
SNOW-1141158: Development Improvement: Enabling local testing using key-pair authentication

### ISSUE THREAD

**Issue by zaramzamzam** [snowflakedb/snowpark-python#1272]
## What is the current behavior?

When developing snowpark-python it is currently only possible to run local tests using username and password.

## What is the desired behavior?

It would be great if both username and password authentication as well as key-pair authentication would work when running tests locally.

## How would this improve `snowflake-snowpark-python`?

This would enable developers using key-pair authentication to easily run local tests.

**Comment by zaramzamzam** [comment]
I added some code to the `conftest.py` file locally when running tests which I can provide in a PR to enable this.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for your contribution ! the team will review and advise

**Comment by sfc-gh-aling** [comment]
hey @zaramzamzam , sorry for the late response.
the connector has the native support for `private_key_file` and `private_key_file_pwd` as connection parameters.
you should be able to just use them and no need to update the conftest file.

**Comment by sfc-gh-aling** [comment]
I'm closing the issue, please free feel to reopen if you want anything else
