### ISSUE TITLE
SNOW-1282839: Add support for SnowURLs

### ISSUE THREAD

**Issue by sfc-gh-dhung** [snowflakedb/snowpark-python#1345]
## What is the current behavior?

Unable to use `snow://` URLs with Snowpark Python APIs like `Session.file.get_stream()`

## What is the desired behavior?

Able to access files with `snow://` URLs.

## How would this improve `snowflake-snowpark-python`?

Compatibility with new Snowflake stage URL type.

**Comment by sfc-gh-sghosh** [comment]
Hello @sfc-gh-dhung ,

Thanks for raising the question, could you explain the application of how and where you want to snow URLs, how Snow Snowflake stage URL are generated etc? Please explain the application scenario.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @sfc-gh-dhung ,

At present this is PrPr.

Regards,
Sujaan
