### ISSUE TITLE
SNOW-1348838: issues relating to FIELD_OPTIONALLY_ENCLOSED_BY

### ISSUE THREAD

**Issue by sfc-gh-svadakath** [snowflakedb/snowpark-python#1443]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python ver: 3.9.6

2. What are the Snowpark Python and pandas versions in the environment?

snowpark python 1.15
pandas: 2.2.2

3. What did you do?
see slack thread https://snowflake.slack.com/archives/C05BVU17AMR/p1714165305047599

4. What did you expect to see?

Expecting no errors. See error
![image (2)](https://github.com/snowflakedb/snowpark-python/assets/122318553/d1e158e2-4793-4e89-99d1-dcbcb61f655d)

**Comment by sfc-gh-aling** [comment]
fixed in PR: https://github.com/snowflakedb/snowpark-python/pull/1455
