### ISSUE TITLE
SNOW-1360263: row_number window function raises a ValueError (index is not in list)

### ISSUE THREAD

**Issue by samuelsongsr** [snowflakedb/snowpark-python#1490]
1. What version of Python are you using?

   Python 3.10.4 (main, May 26 2022, 13:33:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

2. What are the Snowpark Python and pandas versions in the environment?

   pandas==2.2.1
   snowflake-snowpark-python==1.15.0

3. What did you do?
  I'm trying to test a row_number() window function and it's raising a ValueError on this line: 
[_plan.py](https://github.com/snowflakedb/snowpark-python/blob/31aad1fc33c263e3b2c3403f3dab160712e00f22/src/snowflake/snowpark/mock/_plan.py#L1854)

```
from datetime import date

from snowflake.snowpark import Row, Window, Session
from snowflake.snowpark.functions import row_number, col


# create some test data
data = [
    Row(id=1, row_date=date(2024, 1, 1), value=1),
    Row(id=2, row_date=date(2024, 1, 1), value=1),
    Row(id=1, row_date=date(2024, 1, 2), value=1),
    Row(id=1, row_date=date(2024, 1, 2), value=100),
    Row(id=2, row_date=date(2024, 1, 2), value=1)
]

# create a local testing session and dataframe
mock_session = Session.builder.config("local_testing", True).create()
test_data = mock_session.create_dataframe(data)

# partition over id and row_date and get the records with the largest values
window = Window.partition_by("id", "row_date").order_by(col("value").desc())
df = test_data.with_column("row_num", row_number().over(window)).where(col("row_num") == 1)

results = df.collect()

```

4. What did you expect to see?
  
   The results should include the following 4 records:
  ```
  Row(id=1, row_date=date(2024, 1, 1), value=1),
  Row(id=2, row_date=date(2024, 1, 1), value=1),
  Row(id=1, row_date=date(2024, 1, 2), value=100),
  Row(id=2, row_date=date(2024, 1, 2), value=1)
  ```
   
   Instead of the above results, a ValueError is raised stating (1 is not in list).

**Comment by tvdboom** [comment]
Any update on this one? I am still encountering this issue on version 1.22.1
