### ISSUE TITLE
SNOW-1475324: Snowpark that enables the ingestion of data from ODBC/JDBC-based sources

### ISSUE THREAD

**Issue by em47390** [snowflakedb/snowpark-python#1762]
## What is the current behavior?
customer would like to ingest data tables into snowflake

## What is the desired behavior?
currently the data source support jdbc/odbc drivers for connection

## How would this improve `snowflake-snowpark-python`?
the ability to import diverse data source into snowflake/snowpark for further integrated processing

**Comment by sfc-gh-sghosh** [comment]
Hello @em47390 ,

Thanks for raising the question.

Using Snowflake's JDBC or ODBC connectors is more straightforward for simple data ingestion tasks such as in this case. You can use these connectors to ingest data directly from ODBC/JDBC-based sources into Snowflake efficiently.

Where as Snowpark is a developer framework provided by Snowflake that allows you to write code in languages like Scala, Java, and Python to interact with Snowflake data. It provides a way to build complex data pipelines, transformations, and analytical applications within the Snowflake environment.

So, I would recommend using Snowflake jdbc and odbc connectors for data ingestion in this scenario.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @em47390 ,

We provided recommendations, closing this issue.

Regards,
Sujan

**Comment by em47390** [comment]
> Hello @em47390 ,
> 
> Thanks for raising the question.
> 
> Using Snowflake's JDBC or ODBC connectors is more straightforward for simple data ingestion tasks such as in this case. You can use these connectors to ingest data directly from ODBC/JDBC-based sources into Snowflake efficiently.
> 
> Where as Snowpark is a developer framework provided by Snowflake that allows you to write code in languages like Scala, Java, and Python to interact with Snowflake data. It provides a way to build complex data pipelines, transformations, and analytical applications within the Snowflake environment.
> 
> So, I would recommend using Snowflake jdbc and odbc connectors for data ingestion in this scenario.
> 
> Regards, Sujan

Thank you Sujan!! We'll bring thesuggestion back and discuss further!
