### ISSUE TITLE
SNOW-1513909: transaction statements are not working as exepcted

### ISSUE THREAD

**Issue by AidenPTHuang** [snowflakedb/snowpark-python#1860]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.11

2. What operating system and processor architecture are you using?

   Snowflake's Python Worksheets

3. What are the component versions in the environment (`pip freeze`)?

   snowflake-snowpark-python==1.15.0

4. What did you do?

        session.sql("begin").collect()
        session.sql("INSERT INTO TEST(ID,NAME)VALUES('ccc','ddd')").collect()
        session.sql("commit").collect()

    This statments are executed successfully in 1.14.0, and failed from 1.15.0 to 1.19.0

5. What did you expect to see?

   Transaction statements should executed successfully. In the query histroy, I found that "begin" and "commit" are executed twice, first is success, second is failed. 

![image](https://github.com/snowflakedb/snowpark-python/assets/5664098/568161ff-db16-4dca-9b53-a812fe13af71)

6. Can you set logging to DEBUG and collect the logs?

  Yes

**Comment by sfc-gh-sghosh** [comment]
Hello @AidenPTHuang ,

Thanks for raising the issue, we are looking into it, will update.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @AidenPTHuang ,

I just checked with Snowpark python connector version 1.16.0 and transaction is working fine without any error, the begin and commit statements are executing only once as per the application logic

Attaching the screenshot for your reference where I executed it twice, so two times you can see begin and commit 

 session.sql("begin").collect()
 session.sql("INSERT INTO MYCSVTABLE1(SEQ,LAST_NAME,FIRST_NAME)VALUES(9191,'QQQQ','RRRR')").collect()
 session.sql("commit").collect()

![Snowpark Transaction](https://github.com/snowflakedb/snowpark-python/assets/75779154/1b623b53-b1a2-487b-979f-16fe3b15ef5c)

Regards,
Sujan

**Comment by AidenPTHuang** [comment]
Hi @sfc-gh-sghosh 

My application is simple:
![image](https://github.com/snowflakedb/snowpark-python/assets/5664098/9d6ef34d-0128-47a3-ad03-4a658326c888)

This application only works in 1.14.0. 
![image](https://github.com/snowflakedb/snowpark-python/assets/5664098/ad08177e-6296-452a-9d17-ffa960e49bf7)

But failed since 1.15.0 ~ latest


Any ideas?

**Comment by AidenPTHuang** [comment]
issue not resolved

**Comment by sfc-gh-sghosh** [comment]
Hello @AidenPTHuang ,

I checked even with latest Snowpark python connector 1.19.0, its working as expected. There is no double commit etc.
Please use latest Snowpark python connector 1.19.0

![image](https://github.com/snowflakedb/snowpark-python/assets/75779154/235f07d5-8f70-4f05-8c08-40b5bc27b14a)
![Commit_image](https://github.com/snowflakedb/snowpark-python/assets/75779154/f4693e62-d07f-493c-a622-8ef73052667f)

Regards,
Sujan
