### ISSUE TITLE
SNOW-1522886: `row_number()` Function Fails on Empty DataFrame with "No Objects to Concatenate" Error

### ISSUE THREAD

**Issue by hima-gopisetty** [snowflakedb/snowpark-python#1882]
Please answer these questions before submitting your issue. Thanks!

**1. What version of Python are you using?**
```
   Python 3.11.8 
```

**2. What are the Snowpark Python and pandas versions in the environment?**

```
  pandas==1.5.3
  snowflake-snowpark-python==1.14.0
```

3. **What did you do?**

    ```python
    from snowflake.snowpark.functions import col, row_number
    from snowflake.snowpark.window import Window
    from snowflake.snowpark.types import StringType, StructField, StructType, TimestampType
    from snowflake.snowpark import Session

    # Create a Snowflake session
    session = Session.builder.configs({"local_testing": True}).create()

    # Define the schema for the DataFrame
    schema = StructType([
        StructField("ROLE_NAME", StringType()),
        StructField("GIT_COMMIT_VALUE", StringType()),
        StructField("RECORD_CREATED_TS", TimestampType())
    ])

    # Create an empty DataFrame with the defined schema
    sf_df = session.create_dataframe([], schema)


    # Define the window specification
    window = Window.partitionBy("ROLE_NAME").orderBy(col("RECORD_CREATED_TS").desc())

    # Apply the row_number() function using the window specification
    sf_ts = sf_df.with_column("RN", row_number().over(window))

    # Show the resulting DataFrame
    sf_ts.show() # issueValueError: No objects to concatenate when using the row_number() function on empty dataframe
    ```

4. **What did you expect to see?**

    I expected to see an empty DataFrame with an additional "RN" column when running. Instead, I encountered the following issue:

    ```
    ValueError: No objects to concatenate
    ```

    The code should handle empty DataFrames gracefully and return an empty DataFrame with the "RN" column added.

**Additional Note:**
```
It's important to mention that the operations described above work as expected when executed in a standard Snowflake session. The issues outlined occur exclusively during local testing with the Snowpark library.
```

**Comment by trakmaker** [comment]
@hima-gopisetty  I believe you are running commands directly in the terminal, that's when I got the error same as yours but  please correct me if I am wrong. Executing the same inside the python environment works fine for me.

PS: I am using very similar configuration as your environment setup

**Comment by sfc-gh-sghosh** [comment]
Hello @hima-gopisetty ,

Thanks for raising the issue.
We are able to reproduce the issue with local_testing and will work on eliminating it.

Regards,
Sujan

**Comment by sfc-gh-aling** [comment]
hey @hima-gopisetty , I believe the issue has been fixed already in the latest release of snowpark python. I ran your code against snowpark 1.20.0 and it works well.

could you try upgrade and see if the issue is gone?

**Comment by sfc-gh-aling** [comment]
I'm closing the issue since there is no response. please free feel to reach out if the issue is still observed.
