### ISSUE TITLE
SNOW-1528937: Pytest Breaks When Using Multiple Filter Clauses

### ISSUE THREAD

**Issue by jordan-herbert1** [snowflakedb/snowpark-python#1894]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.11

2. What are the Snowpark Python and pandas versions in the environment?

   pandas==1.4.3
   snowflake-snowpark-python==1.14.0

3. What did you do?

   When filtering using `session.table`, if multiple filters or `when` clauses are applied to the same table the unit test fails with the response "['IndexError: single positional indexer is out-of-bounds'](https://stackoverflow.com/questions/42739327/iloc-giving-indexerror-single-positional-indexer-is-out-of-bounds)"

4. What did you expect to see?

   Unit tests passing

**Comment by sfc-gh-aalam** [comment]
can you share a minimal repro

**Comment by sfc-gh-sghosh** [comment]
Hello @jordan-herbert1 ,

Thanks for raising the issue, could you share the code snippet to reproduce the issue.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @jordan-herbert1 ,


Could you share the code snippet to reproduce the issue.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @jordan-herbert1 ,

Closing the issue, please reopen when you have the code snippet.

Regards,
Sujan
