### ISSUE TITLE
SNOW-1529332: Expose DataFrame.create_or_replace_dynamic_table since dynamic table is no longer in preview

### ISSUE THREAD

**Issue by padhia** [snowflakedb/snowpark-python#1897]
## What is the current behavior?

`DataFrame.create_or_replace_dynamic_table` function is [hidden](https://github.com/snowflakedb/snowpark-python/blob/39dbc18fcef1a52f7169152085bc10bb09660c7a/src/snowflake/snowpark/dataframe.py#L3411) from the documentation

## What is the desired behavior?
Please allow this function to be fully supported and documented.

## How would this improve `snowflake-snowpark-python`?
snowpark will catch up with the corresponding SQL feature

**Comment by sfc-gh-sghosh** [comment]
Hello @padhia ,

Thanks for raising the issue, will check about this feature and update.

Regards,
Sujan
