### ISSUE TITLE
SNOW-1569878: Creating Dynamic Table using Snowpark does not support all options

### ISSUE THREAD

**Issue by padhia** [snowflakedb/snowpark-python#2019]
## What is the current behavior?

`DataFrame.create_or_replace_dynamic_table()` function doesn't support all parameters supported by the SQL version

## What is the desired behavior?

Support options supported by the SQL version, specifically:
1. ability to create `TRANSIENT ` dynamic tables
2. Option: `REFRESH_MODE`
3. Option: `INITIALIZE`
4. Option: `CLUSTER BY`
5. Option: `DATA_RETENTION_TIME_IN_DAYS`
6. Option: `MAX_DATA_EXTENSION_TIME_IN_DAYS`

## How would this improve `snowflake-snowpark-python`?

Allows Snowpark to complement/replace SQL as the sole language for DDLs. This is especially important for creating objects that support `SELECT` statements such as Dynamic tables and Views

## References, Other Background
https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table#syntax

**Comment by sfc-gh-sghosh** [comment]
Hello @padhia ,

Thanks for raising the issue.
Dynamic table support has been added in Snowpark Python 1.17.0, but it is still experimental, and not all features are supported. will update about the plan.

Regards,
Sujan

**Comment by sfc-gh-aalam** [comment]
@padhia do you also need the option for `IF NOT EXISTS`?

**Comment by padhia** [comment]
That'd be certainly nice. Maybe a parameter that determines what happens if the table already exists. For example: `mode` parameter with following values:

- `overwrite` translates to `create or replace`
- `skip` translates to `if not exists`
- `error` (default) translates to simply `create`

**Comment by sfc-gh-aalam** [comment]
@padhia setting default to error will be a breaking change so I would not change that. But I'll consider add a `mode` based on your suggestion. We do something similar in `DataFrame.write.save_as_table`
