### ISSUE TITLE
SNOW-1677435: Session builder does not check for `private_key_path` when connecting using key-pair authentication

### ISSUE THREAD

**Issue by sfc-gh-ccardillo** [snowflakedb/snowpark-python#2343]
(must use `key_path_file`)

Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

3.10.11

2. What operating system and processor architecture are you using?

macOS-14.6.1-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

(Cannot copy/paste)
snowflake-connector-python==3.11.0

4. What did you do?

Tried to create a session based on a connection created via the snow CLI. In short, snow CLI stores `key_path_path` in the config.tom, whereas the snowpark connector looks for `key_path_file`. Adding `key_path_file` to the relevant connection block in config.toml resolves the issue.

5. What did you expect to see?

I expected the connection created with snow CLI to work out of the box in the snowpark connector

**Comment by sfc-gh-sghosh** [comment]
Hello @sfc-gh-ccardillo ,

Thanks for raising the issue, could you please provide more detail, how you using snowcli with snowpark, are you creating a snowpark project using snowcli ? 

https://docs.snowflake.com/en/developer-guide/snowflake-cli-v2/snowpark/overview

Could you please provide the code snippet about the issue you hitting?

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @sfc-gh-ccardillo ,

I guess you hitting this error, https://github.com/snowflakedb/snowflake-cli/issues/1480
and this issue is fixed.

I am able to reproduce the above issue as well.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Closing the issue as the fix rolled out in snowcli 3.0
