### ISSUE TITLE
SNOW-1779562: Support Python 3.13

### ISSUE THREAD

**Issue by nembaugh** [snowflakedb/snowpark-python#2546]
## What is the current behavior?
snowpark-python does not support Python 3.13

## What is the desired behavior?
snowpark-python supports Python 3.13

## How would this improve `snowflake-snowpark-python`?
Enables snowpark usage with most current and performant Python.

## References, Other Background
At time of writing 3.11 is the latest Python supported, meaning 3.12 has been out for > 1 year and still has no support. This is tracked in #1253

**Comment by AdamKane** [comment]
Can't install with my version of python.

**Comment by sfc-gh-sghosh** [comment]
Hello @nembaugh ,

Thanks for raising the issue, at present python 3.13 is not yet supported for snowpark.
Will let you know when it will be.

The supported versions of Python are:
    3.9
    3.10
    3.11
    3.12


Regards,
Sujan

**Comment by tvdboom** [comment]
@sfc-gh-sghosh  Does snowpark 1.24.0 support Python 3.12? It doesn't look like it
<img width="587" alt="image" src="https://github.com/user-attachments/assets/49324a51-f029-4d84-95d6-9f13eb80f237">

**Comment by sfc-gh-sghosh** [comment]
Hello @tvdboom ,

Thanks for the update.
Yes, with python 3.12 snowpark python 1.24/23/22/19 etc is not getting installed, getting above error.
Will work on fix and update.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @tvdboom 

Support for Python 3.12 is expected by the end of Nov 2024. At this moment, it is not supported. We will update the document.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @nembaugh ,

Python 3.13 will be supported by Feb end 2024 tentatively.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Python 3.13 will be supported by Feb end 2024 tentatively.

**Comment by rd-malte-koch** [comment]
any current plans about this? :)

**Comment by devMalteK** [comment]
any news on this. issues is closed, but python3.13 is still not supported. 🙃

**Comment by numericOverflow** [comment]
Agreed.  Any update on this?
