### ISSUE TITLE
Force schema for a list of dictionaries returns NULLs

### ISSUE THREAD

**Issue by davidvesp** [snowflakedb/snowpark-python#414]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

3.8.10 64 bits

2. What operating system and processor architecture are you using?

Windows 11

3. What are the component versions in the environment (`pip freeze`)?

asn1crypto==1.5.1
asttokens==2.0.5
azure-core==1.24.2
azure-monitor-opentelemetry-exporter==1.0.0b6
backcall==0.2.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.0.12
cloudpickle==2.0.0
colorama==0.4.5
cryptography==36.0.2
debugpy==1.6.2
decorator==5.1.1
Deprecated==1.2.13
entrypoints==0.4
executing==0.8.3
idna==3.3
ipykernel==6.15.1
ipython==8.4.0
isodate==0.6.1
jedi==0.18.1
jupyter-client==7.3.4
jupyter-core==4.11.1
matplotlib-inline==0.1.3
msrest==0.7.1
nest-asyncio==1.5.5
ntlm-auth==1.5.0
numpy==1.23.1
oauthlib==3.2.0
opentelemetry-api==1.12.0rc2
opentelemetry-sdk==1.12.0rc2
opentelemetry-semantic-conventions==0.32b0
oscrypto==1.3.0
packaging==21.3
pandas==1.4.3
parso==0.8.3
pickleshare==0.7.5
prompt-toolkit==3.0.30
psutil==5.9.1
pure-eval==0.2.2
pyarrow==6.0.1
pycparser==2.21
pycryptodomex==3.15.0
Pygments==2.12.0
PyJWT==2.4.0
pyOpenSSL==22.0.0
pyparsing==3.0.9
pypiwin32==223
python-dateutil==2.8.2
pytz==2022.1
pywin32==304
pyzmq==23.2.0
requests==2.28.1
requests-negotiate-sspi==0.5.2
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
six==1.16.0
snowflake-connector-python==2.7.9
snowflake-snowpark-python==0.8.0
stack-data==0.3.0
tornado==6.2
traitlets==5.3.0
typing_extensions==4.3.0
urllib3==1.26.10
wcwidth==0.2.5
wrapt==1.14.1

4. What did you do?

Firstly, create a dataframe from a list of dictionaries
```
myList = [
	{
		'foo':12,
		'bar':14
	},
	{
		'foo':52,
		'bar':641
	},
	{
		'foo':6,
		'bar':84
	}
]
```

dfmyList = session.create_dataframe(myList)
print(dfmyList.schema)
```
StructType([StructField('FOO', LongType(), nullable=False), StructField('BAR', LongType(), nullable=False)])
```

dfmyList.show()
```
-----------------
|"FOO"  |"BAR"  |
-----------------
|12     |14     |
|52     |641    |
|6      |84     |
-----------------
```

After that, I try the same but forcing the schema:

from snowflake.snowpark.types import IntegerType, StringType, StructType, StructField, LongType, ArrayType, BooleanType, DateType
-- from the output of the previous dfmyList.schema
myListSchema = StructType([StructField('FOO', LongType(), nullable=False), StructField('BAR', LongType(), nullable=False)])

dfmyListSchema = session.create_dataframe(myList, myListSchema)

print(dfmyListSchema.schema)
```
StructType([StructField('FOO', LongType(), nullable=True), StructField('BAR', LongType(), nullable=True)])
```

dfmyListSchema.show()
```
-----------------
|"FOO"  |"BAR"  |
-----------------
|NULL   |NULL   |
|NULL   |NULL   |
|NULL   |NULL   |
-----------------
```

5. What did you expect to see?
```
 -----------------
|"FOO"  |"BAR"  |
-----------------
|12     |14     |
|52     |641    |
|6      |84     |
-----------------
```

6. Can you set logging to DEBUG and collect the logs?

No

**Comment by sfc-gh-yixie** [comment]
@sfc-gh-jdu Do we support schema when creating a dataframe from a dict?

**Comment by sfc-gh-jdu** [comment]
Ack the bug. We will work on this next week.

**Comment by sfc-gh-jdu** [comment]
#419 fixes this issue (see reason in PR description)
