### ISSUE TITLE
SNOW-641391: add filter join types (leftsemi/left_semi and leftanti/left_anti)

### ISSUE THREAD

**Issue by ChuliangXiao** [snowflakedb/snowpark-python#424]
## What is the current behavior?
Four types of joins (*inner*, *full*, *left*, *right*) are supported in `.join()`
## What is the desired behavior?
Add two filter joins: [*semi*](https://en.wikipedia.org/wiki/Relational_algebra#Semijoin_(%E2%8B%89)(%E2%8B%8A)) and [*anti*](https://en.wikipedia.org/wiki/Relational_algebra#Antijoin_(%E2%96%B7))
## How would this improve `snowflake-snowpark-python`?
Expand `.join()` with consistent systax.
## References, Other Background
Filter joins are supported by other SQL engines like [Spark](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.join.html) and [U-SQL](https://docs.microsoft.com/en-us/u-sql/statements-and-expressions/select/from/joins/semijoin)

**Comment by sfc-gh-sfan** [comment]
Thanks for the feedback. I think `left semi` and `left anti` is supported according to what I read [here](https://github.com/snowflakedb/snowpark-python/blob/5ed94f4a2fd99ed510c5792e4f6b0981a174e619/src/snowflake/snowpark/_internal/analyzer/binary_plan_node.py#L27), though the [documentation](https://github.com/snowflakedb/snowpark-python/blob/2486a03811f33f05f7e5a9d28575686ccd23ddb9/src/snowflake/snowpark/dataframe.py#L1603) could be improved.

**Comment by sfc-gh-sfan** [comment]
Improved documentation in https://github.com/snowflakedb/snowpark-python/pull/428
