### ISSUE TITLE
SNOW-641398: CREATE TABLE privilege required on schemas when appending data

### ISSUE THREAD

**Issue by badge** [snowflakedb/snowpark-python#425]
I am trying to insert data into a Snowflake table using a role which has `insert` privileges on table `my_table`, but _not_ `create table` on `my_table`'s schema. I expect this to work as follows:

```python
target_table = session.table("my_schema.my_table")
insert_table = session.create_dataframe(
    [[1]],
    schema=target_table.schema
)
insert_table.write.save_as_table("my_schema.my_table", mode="append")
```

However, on running this, I get the error `Insufficient privileges to operate on schema 'MY_SCHMEA'`. Granting `CREATE TABLE` privileges on `my_schema` to the role being used by `session` resolves the problem, but should be unnecessary when I only want to append data (and the table already exists).

**Comment by sfc-gh-sfan** [comment]
This is an interesting bug. Today `save_as_table` append mod tries to do a `CREATE TABLE IF NOT EXISTS` first, and it looks like this requires `CREATE TABLE` privilege on the schema even if the table exists. The alternative is probably doing a `DESC`, but it means one more round trip which might have performance implications. 

Any thoughts? @sfc-gh-yixie @sfc-gh-jdu (tagged you two based on git annotation :P)

**Comment by sfc-gh-jdu** [comment]
I think we can check whether the table exists or not first (using `SHOW`) instead of running `CREATE TABLE IF NOT EXISTS` directly. It should be an easy fix.
