### ISSUE TITLE
SNOW-652229: Documentation error: `save_as_table` doesn't accept a table_type parameter

### ISSUE THREAD

**Issue by mbkupfer** [snowflakedb/snowpark-python#452]
Please answer these questions before submitting your issue. Thanks!
Sorry for skipping over the boilerplate questions, but I don't think any would be applicable. I'm just wanting to point out an inconsistency in [this documentation section](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.DataFrameWriter.save_as_table) (which also comes up in the alias and other related functions). 

The documentation shows this example to create a temp table
```
>>> df = session.create_dataframe([[1,2],[3,4]], schema=["a", "b"])
>>> df.write.mode("overwrite").save_as_table("my_table", table_type="temporary")
```
but this will throw an error since `table_type` is not an accepted argument:

```
TypeError: save_as_table() got an unexpected keyword argument 'table_type'
```

**Comment by sfc-gh-jdu** [comment]
Hey @mbkupfer, what's your snowpark version? This argument is added in snowpark 0.8.0.

**Comment by mbkupfer** [comment]
Oh shoot, you are so right! I'm on 0.7.0. Must've missed the version bump.
