### ISSUE TITLE
SNOW-656385: Cannot import snowflake.snowpark.session in Google Colab

### ISSUE THREAD

**Issue by caroheymes** [snowflakedb/snowpark-python#469]
Please answer these questions before submitting your issue. Thanks!

1. Pyrhon version : 3.8
   3.8.1 (default, Jan  8 2020, 22:29:32) \n[GCC 7.3.0]

2. What operating system and processor architecture are you using?
Google colab with conda installation through
````
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
````

Conda info : 
```
active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.1.final.0
       virtual packages : __linux=5.4.188=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.22.0 CPython/3.8.1 Linux/5.4.188+ ubuntu/18.04.6 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False4````

   Replace with the output of `python -c 'import platform; print(platform.platform())'`

4. What are the component versions in the environment (`pip freeze`)?
 ```
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.5.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asn1crypto==1.3.0
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==4.1.0
cachetools==5.2.0
certifi==2022.6.15
cffi==1.14.0
chardet==3.0.4
charset-normalizer==2.1.1
cloudpickle==2.0.0
conda==4.14.0
conda-package-handling==1.6.0
cryptography==35.0.0
cytoolz==0.11.0
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.16.2
filelock==3.6.0
frozenlist==1.2.0
google-auth==2.11.0
google-colab==1.0.0
idna==2.8
importlib-resources==5.2.0
ipykernel==6.9.1
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
json5==0.9.6
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.2
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyter-server==1.18.1
jupyterlab==3.4.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.12.0
jupyterlab-widgets==1.0.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==0.8.4
multidict==5.2.0
nbclassic==0.3.5
nbclient==0.5.13
nbconvert==6.4.4
nbformat==5.3.0
nest-asyncio==1.5.5
notebook==6.4.12
numpy==1.17.5
oscrypto==1.2.1
packaging==21.3
pandas==1.0.5
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
portpicker==1.3.1
prometheus-client==0.14.1
prompt-toolkit==3.0.20
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycosat==0.6.3
pycparser==2.19
pycryptodomex==3.15.0
Pygments==2.11.2
PyJWT==2.4.0
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.18.0
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2022.1
pyu2f==0.1.5
pyzmq==22.3.0
qtconsole==5.3.2
QtPy==2.2.0
requests==2.22.0
rsa==4.9
ruamel-yaml==0.15.87
Send2Trash==1.8.0
sip==4.19.13
six==1.14.0
sniffio==1.2.0
snowflake-connector-python==2.7.12
snowflake-snowpark-python==0.8.0
soupsieve==2.3.1
stack-data==0.2.0
terminado==0.13.1
testpath==0.6.0
toolz==0.11.2
tornado==6.1
tqdm==4.42.1
traitlets==5.1.1
typing-extensions==4.3.0
urllib3==1.25.8
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.58.0
widgetsnbextension==3.5.2
yarl==1.6.3
zipp==3.8.0
```

5. What did you do?

 Cannot import from snowflake.snowpark.session import Session 
 
6. What did you expect to see?
 Googe fails to import snowflake.snowpark.session. I cannot soart a  Snowflake session in colab

cf google colab notebook
https://colab.research.google.com/drive/1tKhlTJ8r_gbwTpwRd3SOv0FBCOm3tgkf?usp=sharing

   What should have happened and what happened instead?

8. Can you set logging to DEBUG and collect the logs?



<!--
If you need urgent assistance reach out to support for escalated issue processing https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge
-->

**Comment by sfc-gh-jdu** [comment]
Hey @caroheymes, what's the error message when import snowpark session?
