### ISSUE TITLE
SNOW-664934: Dataframe schemas don't persist between Pandas and Snowpark

### ISSUE THREAD

**Issue by elongl** [snowflakedb/snowpark-python#504]
1. What version of Python are you using?

Python 3.8

2. What operating system and processor architecture are you using?

Snowflake Python UDF

3. What are the component versions in the environment (`pip freeze`)?

Only snowflake-snowpark-python

4. What did you do?

Snowpark has a problem / bug that it does not maintain the types between Pandas and Snowpark, nor does it allow to manually set its schema.

For instance,
```py
df1 = session.sql(sql).to_pandas()
df2 = session.create_dataframe(df)
```

The timestamp field on `df1` with `TimestampType` has become a `LongType`.

I've also tried to store the schema and use it, but same results.

```py
df1 = session.sql(sql)
df1_schema = df1.schema
df1 = df1.to_pandas()
df2 = session.create_dataframe(df, df1_schema)
```

This stops me from being able to write the `DataFrame` back to the table as it needs to be of `TimestampType` rather than `LongType`.

5. What did you expect to see?

The schemas persist among the conversions.

**Comment by sfc-gh-jdu** [comment]
Do you have a minimum repro for this? We'll look into it next week

**Comment by elongl** [comment]
![image](https://user-images.githubusercontent.com/30181361/191853438-d73c7644-7a0c-4d7f-bda8-1d2dcccdfcc9.png)

@sfc-gh-jdu Just take any Timestamp column, convert it to Pandas, convert it back, and it'll change to Long type.
Look at the `DETECTED_AT` field in the image.

**Comment by elongl** [comment]
@sfc-gh-jdu 
Hi! Any updates?
I'd love to supply additional information if needed.
Appreciate your help.

**Comment by sfc-gh-sfan** [comment]
@elongl : We are going to look into this in the next two weeks. Stay tuned!

**Comment by elongl** [comment]
Fixing it for me specifically will not do since I'm developing a package and I want it to work for other users as well.
Isn't there a way to enforce the types to stick?

**Comment by sfc-gh-sfan** [comment]
It is a bit more complicated. When converting a `pandas` dataframe to a snowpark dataframe, we need to use parquet file as an intermediate and create a table out of it. The schema is determined by the `infer_schema` result from the parquet file.

But there is a potential solution to accept a schema that overrides so we skip `infer_schema` altogether. @sfc-gh-jdu , @sfc-gh-yixie : What do you think?

**Comment by sfc-gh-sfan** [comment]
@elongl - While we are working on schema override when creating snowpark dataframe from pandas dataframe, please note that this does not fully work with timestamp until the behavior change I mentioned is rolled out (check https://github.com/snowflakedb/snowpark-python/pull/557#discussion_r993923546). 

Regardless of the process of server side behavior change about parquet file new logical time, we think being able to specify `schema` is still useful.

**Comment by jacob-martin-slalom** [comment]
Are there any updates on this by chance? This is a major blocker for our team's SnowPark implementation.

**Comment by sfc-gh-sfan** [comment]
Hi @jacob-martin-slalom , there are issues related to rolling out the server side change to use new parquet logical type, for which I don't have a clear answer of what the ETA looks like (cc @sfc-gh-yuliu ).

As for schema override, that should be part of the first release in 2023: https://github.com/snowflakedb/snowpark-python/pull/557#issuecomment-1279218902.
