### ISSUE TITLE
SNOW-683625: Standardize RLIKE (REGEXP/RLIKE in Snowflake) and add CONTAINS method to Column

### ISSUE THREAD

**Issue by ChuliangXiao** [snowflakedb/snowpark-python#571]
This is more of Snowflake syntax issue.
## What is the current behavior?
To match any string containing `ABC`, `.rlike('.*ABC.*')`
Also Snowflake [CONTAINS](https://docs.snowflake.com/en/sql-reference/functions/contains.html) is not available for [Snowpark `Column`](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.Column) yet.
## What is the desired behavior?
To match any string containing `ABC`, `.rlike('ABC')`
## How would this improve `snowflake-snowpark-python`?
Make `RLIKE` consistent with other SQL, i.e. [pySpark](https://spark.apache.org/docs/latest/api/python//reference/pyspark.sql/api/pyspark.sql.Column.rlike.html) and [MySQL](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp)
## References, Other Background
According to [Snowflake Docs on REGEXP](https://docs.snowflake.com/en/sql-reference/functions/regexp.html),
> The function implicitly anchors a pattern at both ends (i.e. `''` automatically becomes `'^$'`, and `'ABC'` automatically becomes `'^ABC$'`). To match any string starting with `ABC`, the pattern would be `'ABC.*'`.

**Comment by sfc-gh-jdu** [comment]
Hi @ChuliangXiao, REGEXP in Snowflake has been there for a while and our Python API should align with Snowflake SQL, so we might not want to change it. But we can add `contains` to Column class, which will satisfy your need described in this issue, right? For now, you can use [`contains`](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.functions.html#snowflake.snowpark.functions.contains) function first as a workaround.

**Comment by ChuliangXiao** [comment]
> Hi @ChuliangXiao, REGEXP in Snowflake has been there for a while and our Python API should align with Snowflake SQL, so we might not want to change it. But we can add `contains` to Column class, which will satisfy your need described in this issue, right? For now, you can use [`contains`](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.functions.html#snowflake.snowpark.functions.contains) function first as a workaround.

Thanks for suggesting the [contains](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.functions.html#snowflake.snowpark.functions.contains) function. Would be great to have `contains` in the `Column` class.
