### ISSUE TITLE
update snowflake-snowpark-python package in Snowflake

### ISSUE THREAD

**Issue by ChuliangXiao** [snowflakedb/snowpark-python#577]
## What is the current behavior?
`snowflake-snowpark-python` [v0.12.0](https://github.com/snowflakedb/snowpark-python/releases/tag/v0.12.0) was released Oct 14th 2022, the [Snowflake Packages](https://docs.snowflake.com/en/sql-reference/info-schema/packages.html) still only has `v0.10.0` as of Oct 26 2022.
## What is the desired behavior?
Synchronize the release `snowflake-snowpark-python`
## How would this improve `snowflake-snowpark-python`?
Make new Snowpark features available for creating **Stored Function** and **Store Procedure**.
## References, Other Background
Here is the list available `snowflake-snowpark-python` in Snowflake
```sql
select * from information_schema.packages 
where language = 'python'
    and package_name = 'snowflake-snowpark-python'
order by to_numeric(split_part(version, '.', 2)) desc
```

**Comment by sfc-gh-jdu** [comment]
Hey @ChuliangXiao, yes this a known issue, and we are currently working on shorting the gap between client and server release for snowpark. We don't have an ETA yet, but will keep you posted on this issue.
