### ISSUE TITLE
SNOW-686233: Ability to Convert 'snowflake.snowpark.dataframe.DataFrame' to spark.sql.DataFrame

### ISSUE THREAD

**Issue by amithadiraju1694** [snowflakedb/snowpark-python#596]
## What is the current behavior?

Creating DataFrame / Executing sql statements on snowflake returns a `snowflake.snowpark.dataframe.DataFrame` by default without an option to convert it to a `spark DataFrame` similar to `to_pandas`.

I'm planning to run snowpark on Databricks env, are  `snowflake.snowpark.dataframe.DataFrame` distributed across spark workers by default ?

## What is the desired behavior?
Provide a `to_spark_df()`

## How would this improve `snowflake-snowpark-python`?

Ability to run execute queries on snowflake and use the post-computation data in other platforms for specific down stream tasks in a distributed way with spark data frames.

## References, Other Background
N/A

**Comment by sfc-gh-aalam** [comment]
Can you help me understand your use case? Snowpark python is designed to interact with your data that resides in snowflake databases and pyspark is designed to work well with data that is in databricks. Are you trying to move data from snowflake to databricks? If yes, why not just use snowpark with snowflake without moving your data out?

**Comment by amithadiraju1694** [comment]
> Can you help me understand your use case? Snowpark python is designed to interact with your data that resides in snowflake databases and pyspark is designed to work well with data that is in databricks. Are you trying to move data from snowflake to databricks? If yes, why not just use snowpark with snowflake without moving your data out?


Thanks for quick update. Our orgs data's in snowflake , but our ML training runs on Spark clusters from Data bricks. We usually use snowflake connector to pull data from snowflake ( and execute some aggregations while we pull as well ) and run our ML training pipelines in data bricks.

We want to use `feast snowflake` as a feature store abstraction , to run on data bricks to fetch the features ( residing in snowflake ) for model training . 

By default `feast snowflake` uses `Snowflake Connector` which returns `arrow_batches` , `arrow_table` or `pandas data frames` which are not as well distributed as `spark data frames`. We want to be able to replace `Snowflake Connector` with `Snowpark Connector` to get the feature data directly as a `spark dataframe` via feast.

**Comment by sfc-gh-aalam** [comment]
Using snowflake connector might still be better for you if you need to transfer data out of snowflake. But if you are open to experiment with snowpark, you could try moving your ML workload to snowflake. With UDFs and UDTFs, you could import most of popular packages for ML and see the performance gains for yourself. Are there any feature gaps that is preventing you to do that?

**Comment by amithadiraju1694** [comment]
> Using snowflake connector might still be better for you if you need to transfer data out of snowflake. But if you are open to experiment with snowpark, you could try moving your ML workload to snowflake. With UDFs and UDTFs, you could import most of popular packages for ML and see the performance gains for yourself. Are there any feature gaps that is preventing you to do that?

Got it. Thanks for suggestion ! We haven't done a feature gap comparison between platforms, might be hard to move ML pipelines to new platform just yet but will do it in future.

If it's not much to ask, could you provide your POV in which approach is faster to convert data to `spark data frame` , our data is in order of 100's of gigs:

1. `fetch_arrow_all (Table) ` -> `to_batches(iterating batches)` -> `to_pandas` -> `spark DF` (or)
2. `fetch_arrow_batches` -> `Iterating batches` -> `to_pandas` -> `spark DF` ?

**Comment by sfc-gh-jhollan** [comment]
Chiming in with a few thoughts as well:
- To original question, the Snowflake Dataframe operates by pushing down the Snowflake the actual transformations / operations, which it can do at massive scale / parallelism / distributed. It requires a connection to a Snowflake account, but whether you run the Python code / Snowpark API on your laptop, in Databricks, or in a Snowflake stored procedure -- it will push the "heavy lifting" of that 100's of gigs or whatever to actually process in Snowflake at scale -- all lazily. So should be very low utilization on Databricks. With that I almost wonder if you even need Spark DF in the picture?
- The other options as mentioned is you could use the Python connector. Behind the scenes Snowpark client library uses the Snowflake library to push the operations to Snowflake, but adds the dataframe abstraction / sql generation on top of it. If you want to use the Python connector directly you can - just may mean a little bit more work. But is flexible if you really wanted to load data into a Spark DF.
- Also worth noting there is also the [Spark Snowflake connector](https://docs.snowflake.com/en/user-guide/spark-connector.html) which runs as a spark plugin and also pushes down some of the work to Snowflake.

Hopefully that makes sense. I'm biased as a product manager on Snowpark but I think the option of using the Snowpark client libraries -- whether you run that python code in Snowflake / Databricks / somewhere else is the optimal approach between overhead / performance / etc. as will push down to Snowflake -- but removes Spark Dataframes from equation.

**Comment by amithadiraju1694** [comment]
> Chiming in with a few thoughts as well:
> 
> * To original question, the Snowflake Dataframe operates by pushing down the Snowflake the actual transformations / operations, which it can do at massive scale / parallelism / distributed. It requires a connection to a Snowflake account, but whether you run the Python code / Snowpark API on your laptop, in Databricks, or in a Snowflake stored procedure -- it will push the "heavy lifting" of that 100's of gigs or whatever to actually process in Snowflake at scale -- all lazily. So should be very low utilization on Databricks. With that I almost wonder if you even need Spark DF in the picture?
> * The other options as mentioned is you could use the Python connector. Behind the scenes Snowpark client library uses the Snowflake library to push the operations to Snowflake, but adds the dataframe abstraction / sql generation on top of it. If you want to use the Python connector directly you can - just may mean a little bit more work. But is flexible if you really wanted to load data into a Spark DF.
> * Also worth noting there is also the [Spark Snowflake connector](https://docs.snowflake.com/en/user-guide/spark-connector.html) which runs as a spark plugin and also pushes down some of the work to Snowflake.
> 
> Hopefully that makes sense. I'm biased as a product manager on Snowpark but I think the option of using the Snowpark client libraries -- whether you run that python code in Snowflake / Databricks / somewhere else is the optimal approach between overhead / performance / etc. as will push down to Snowflake -- but removes Spark Dataframes from equation.

Thanks for inputs, agree with your thoughts. It's just that our data scientists, do want to add some customization to features data once pulled from snowflake + and want to make it distributed as well, and hence the need to convert to spark data frames. But will try to utilize snowflake connector to the best.

**Comment by sfc-gh-jhollan** [comment]
Sounds good @amithadiraju1694 - happy to explore more of what we could do help your team here too. Feel free to reach out anytime or as you learn more. As you continue exploring would be keen to get an update and what we could consider for your team as well. Jeff.hollan@snowflake.com - happy to help.

**Comment by patchatarch** [comment]
Just want to add my 2 cents here.

Currently Im using snowpark in databricks, which is great.

Now, the only way that I can view a snowpark dataframe is doing snowpark_df.show()
Although this works and all, in the databricks notebook, it is display as a text and its if the dataframe is too big, I won't be able to understand the log of snowpark_df.show() as shown below.

![image](https://user-images.githubusercontent.com/97180115/217571620-e9956e65-1f24-4a40-8af1-9414156a6f20.png)


now, Databricks has a very cool way of displaying pyspark rdds by using display(df) which allows me to view the content of the dataframe better.
![image](https://user-images.githubusercontent.com/97180115/217580787-0ff11038-0ca2-47d5-a352-44e2f6f7c0e7.png)

I am not able to use display for snowpark df. Its not supported. The only way I can think of is convert **snowflake.snowpark.dataframe.DataFrame** to **spark.sql.DataFrame** but I don't see any straightforward way to do it.

**Comment by jeffhollan** [comment]
Do you know if this custom display function works with pandas? Converting to_pandas is supported and wondering if that works better?
