### ISSUE TITLE
SNOW-688157: Sidebar links don't work in online documentation

### ISSUE THREAD

**Issue by mbkupfer** [snowflakedb/snowpark-python#605]
Clicking the sidebar links return a 404 error like this:

![image](https://user-images.githubusercontent.com/6313008/199597898-b3d6ff62-6ab0-4099-ba9b-883c991fcecf.png)

Example link: https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.functions.html

**Comment by mbkupfer** [comment]
Thanks. Yeah I noticed the improved version too. I'm just still on v0.12 as I wasn't sure if v1.0 had any breaking change or not as per [semantic versioning spec](https://semver.org/). I guess this is a good place to ask, were there any breaking changes to be aware of?

**Comment by sfc-gh-jdu** [comment]
No breaking change between 0.12.0 and 1.0.0. BTW, we just fixed the old link, which now is redirected to the index page of docs. I will close this ticket for now, but feel free to reopen it if you have any other questions. Thanks!
