### ISSUE TITLE
SNOW-689375: Location of Dependency Manager of Columns

### ISSUE THREAD

**Issue by lawrence-vo** [snowflakedb/snowpark-python#612]
Apologies if this is not the appropriate forum to ask, I am asking this for education purposes.

Let's say i have the following example:
```
df = session.table("some_db.some_schema.some_table)
df = df.with_column('.test', F.sql_expr("case when coalesce(foo, bar) then 1 else 0 end"))
df.select('.test').show(10)
```

Where in the repository is the section in which  the `F.sql_expr("case when coalesce(foo, bar) then 1 else 0 end"))` determines that it depends on columns `foo` and `bar`.

Thanks!

**Comment by sfc-gh-yixie** [comment]
@lawrence-vo The client side currently doesn't parse the sql text to understand that it depends on which columns. To be conservative, `.test` depends on all columns. This might be something we'll look into in the future.
If you use the function `when` then the client side knows `.test` depends on foo and bar.

**Comment by lawrence-vo** [comment]
@sfc-gh-yixie Thanks!
