### ISSUE TITLE
SNOW-706286: snowpark SSL using Windows certificate store

### ISSUE THREAD

**Issue by xchray** [snowflakedb/snowpark-python#633]
today our company network intercept the network certificates under zero trust principle. In Windows system, this caused snowpark python program not able to start. 

## What is the desired behavior?
snowpark should provide possibility in Windows provide SSL verification from windows certificate store. 

## How would this improve `snowflake-snowpark-python`?
please kindly implement a similar option which in Windows using windows certificate store is possible. 

## References, Other Background
In JAVA, or PIP or Conda, it is possible to use windows certificate store. Java is using jvm parameter, conda and pip needs addtional package installed.

**Comment by xchray** [comment]
HTTPSConnectionPool(host='xxxx.east-us-2.azure.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/authenticator-request?request_guid=1ad7d251-a3ff-4e2d-a7e4-278e6c3de8f0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

this is the error caused by the certificate issue.

**Comment by sfc-gh-jdu** [comment]
Hey @xchray, thanks for feedback. That's on our radar and we will keep you posted.

**Comment by suyogpatil2002** [comment]
What is the fix for this error? We are getting same error and not sure if it is because any network certificate or what? Please guide step by step on resolving this issue.

**Comment by xchray** [comment]
are you guy going to do this? what is your roadmap on this?
