### ISSUE TITLE
SNOW-707457: createDataFrame losses column Information when schema is a tuple

### ISSUE THREAD

**Issue by orellabac** [snowflakedb/snowpark-python#634]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

 Python 3.8.13

2. What operating system and processor architecture are you using?

   Linux-5.15.0-47-generic-x86_64-with-glibc2.29

3. What are the component versions in the environment (`pip freeze`)?

asn1crypto==1.5.1
build==0.9.0
cloudpickle==2.0.0
ipywidgets==8.0.2
jupyter==1.0.0
jupyter-console==6.4.4
jupyterlab-widgets==3.0.3
numpy==1.23.4
oscrypto==1.3.0
pandas==1.5.1
pep517==0.13.0
plotly==5.11.0
pycryptodomex==3.15.0
PyJWT==2.6.0
pyOpenSSL==22.1.0
pytz==2022.6
qtconsole==5.4.0
QtPy==2.3.0
shortuuid==1.0.10
snowflake-connector-python==2.8.1
snowflake-snowpark-python==1.0.0
snowpark-extensions @ file:///workspace/snowpark-extensions-py/dist/snowpark_extensions-0.0.1-py3-none-any.whl
tenacity==8.1.0
widgetsnbextension==4.0.3

4. What did you do?

  df = session.createDataFrame(
    [(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0)],
    schema=("ID", "V"))  
df.snow()

5. What did you expect to see?

---------------
|"_1"  |"_2"   |
---------------
|1     |1.0   |
|1     |2.0   |
|2     |3.0   |
|2     |5.0   |
|2     |10.0  |
---------------
   What should have happened and what happened instead?
```
---------------
|"ID"  |"V"   |
---------------
|1     |1.0   |
|1     |2.0   |
|2     |3.0   |
|2     |5.0   |
|2     |10.0  |
---------------
```

We notice that this look as a simple error in the library:

In session.py

```
            if isinstance(schema, list):
                names = schema
            new_schema = reduce(
                merge_type,
                (infer_schema(row, names) for row in data),
            )
```

should be:
```
            if isinstance(schema, Iterable):
                names = schema
            new_schema = reduce(
                merge_type,
                (infer_schema(row, names) for row in data),
            )
```

**Comment by sfc-gh-jdu** [comment]
@orellabac good catch! Since it's a simple fix, would you like to create a PR for it? (we can also do it of course)

**Comment by orellabac** [comment]
Ok I just sent the PR
