### ISSUE TITLE
SNOW-717136: Extract resources from python module

### ISSUE THREAD

**Issue by danielhstahl** [snowflakedb/snowpark-python#639]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.8.15

2. What operating system and processor architecture are you using?

Linux-5.4.219-126.411.amzn2.x86_64-x86_64-with-glibc2.10

3. What are the component versions in the environment (`pip freeze`)?

Snowflake connector: 2.8.3
Snowpark:1.0.0

4. What did you do?

   Access files/resources inside a python package.  I imported MLFlow inside a Snowflake Stored procedure, and it errors here: https://github.com/mlflow/mlflow/blob/master/mlflow/utils/autologging_utils/versioning.py#L73. 

`No such file or directory: 'tmp/tmp_te6g509'`

The directory path the error is referencing is created here: https://github.com/mlflow/mlflow/blob/master/mlflow/utils/autologging_utils/versioning.py#L70-L72.

My hypothesis is that the MLFlow library, which is zipped and sent to the Snowpark stage, is extracted into tmp.  What I don't understand is why the resource doesn't seem to exist there.

5. What did you expect to see?

It correctly identifying where the resource is in the library and giving me the correct path to that resource.

6. Can you set logging to DEBUG and collect the logs?

   ```
   import logging

   for logger_name in ('snowflake.snowpark', 'snowflake.connector'):
       logger = logging.getLogger(logger_name)
       logger.setLevel(logging.DEBUG)
       ch = logging.StreamHandler()
       ch.setLevel(logging.DEBUG)
       ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
       logger.addHandler(ch)
   ```

**Comment by sfc-gh-sfan** [comment]
What's your use case for using MLFlow? 

My understanding is that the files are zipped and snowflake directly uses zipimport to import the files, and as a result, I don't think files are extracted. Though you could extract the files by doing the following in your stored proc, but I'm not confident that MLFlow can just run as is because it might require external internet access:

```
    import os
    import sys
    import zipfile

    IMPORT_DIRECTORY_NAME = "snowflake_import_directory"
    import_dir = sys._xoptions[IMPORT_DIRECTORY_NAME]

    input_file = import_dir + 'mlflow.zip'
    output_dir = '/tmp/mlflow'

    with zipfile.ZipFile(input_file, 'r') as zip_ref:
        zip_ref.extractall(output_dir)
```

**Comment by danielhstahl** [comment]
Wow, that worked!  I added `sys.path.insert(0, output_dir)` to your code and then ran `import mlflow` with no issue.  Just wish there was a less janky way to do it but at least it works.

**Comment by sfc-gh-sfan** [comment]
@danielhstahl Stay tuned :) MLFlow support is definitely on our roadmap.

**Comment by danielhstahl** [comment]
For posterity: 

MLFlow now packages the yaml into Python code at build time; circumventing the entire issue: https://github.com/mlflow/mlflow/pull/7577
