### ISSUE TITLE
SNOW-717385: Missing overloads for asc/desc/asc_nulls_first/asc_null_last/desc_null_first/desc_null_last

### ISSUE THREAD

**Issue by orellabac** [snowflakedb/snowpark-python#640]
## What is the current behavior?

Current all this functions exists but only for a column object. There is no equivalent in .functions namespace

## What is the desired behavior?

It is very common to use a syntax where they are used as import from functions.

## How would this improve `snowflake-snowpark-python`?

It makes easier moving code from spark to snowpark.

**Comment by sfc-gh-sfan** [comment]
I might be missing something, but in `pyspark`, `desc_nulls_first` is also a function for columns. I wonder why this could make spark migration easier. Do you have some example spark code?

**Comment by orellabac** [comment]
In pyspark the function exists both in functions and in Columns. The idea is to make the api more compatible with spark to reduce the friction of adoption

**Comment by sfc-gh-sfan** [comment]
I'm sorry you are right. I saw it in https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.desc_nulls_first.html?highlight=desc_nulls_first#pyspark.sql.functions.desc_nulls_first.
