### ISSUE TITLE
SNOW-719806: Python dataframe is not showing rows in expected order when sorted 

### ISSUE THREAD

**Issue by narendra-meenaga** [snowflakedb/snowpark-python#646]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   python 3.8.10

2. What operating system and processor architecture are you using?

   macOS-10.16-x86_64-i386-64bit

3. What are the component versions in the environment (`pip freeze`)?

  asn1crypto==1.5.1
  certifi==2022.12.7
  cffi==1.15.1
  charset-normalizer==2.1.1
  cloudpickle==2.0.0
  cryptography==38.0.4
  filelock==3.8.2
  idna==3.4
  oscrypto==1.3.0
  pycparser==2.21
  pycryptodomex==3.16.0
  PyJWT==2.6.0
  pyOpenSSL==22.1.0
  pytz==2022.7
  requests==2.28.1
  snowflake-connector-python==2.9.0
  snowflake-snowpark-python==1.0.0
  typing-extensions==4.4.0
  urllib3==1.26.13

4. What did you do?

- Create snowpark dataframe
- Create a UDF to process a column
- Create new column to use the above UDF 
- Sort the Rows in order of a column
- Select few columns to show .One of the column name  should be the new column created.
- Observe that rows are not displayed in the expected order

   ** **

    Example code can be observed as shown below

```
schema = StructType([StructField('emp_id',IntegerType()),StructField('emp_name',StringType()),StructField('salary',IntegerType()), ])  
df = session.create_dataframe([[101,'Sachin Tendulkar',1200],[102,'Michael Bevan',2000],[103,'Glenn Mcgrath',500],[104,'Malcolm Marshall',3500]],schema)

@udf(name='first_name',input_types=[StringType()],return_type=StringType(),replace=True)
def first_name(input):
    return input.split(' ')[0]

df.withColumn('emp_first_name',first_name('emp_name'))\
    .sort(col('salary').asc())\
    .select('emp_id','emp_first_name','salary')\
    .show()
```

Different example outputs observed are as below.Observe that records are not displayed in the ascending order of 'salary'

```
------------------------------------------
|"EMP_ID"  |"EMP_FIRST_NAME"  |"SALARY"  |
------------------------------------------
|104       |Malcolm           |3500      |
|103       |Glenn             |500       |
|102       |Michael           |2000      |
|101       |Sachin            |1200      |
------------------------------------------
```

```
------------------------------------------
|"EMP_ID"  |"EMP_FIRST_NAME"  |"SALARY"  |
------------------------------------------
|103       |Glenn             |500       |
|104       |Malcolm           |3500      |
|102       |Michael           |2000      |
|101       |Sachin            |1200      |
------------------------------------------
```

7. What did you expect to see?

   Expected output in the above example is as below
   
```
------------------------------------------
|"EMP_ID"  |"EMP_FIRST_NAME"  |"SALARY"  |
------------------------------------------
|103       |Glenn             |500       |
|101       |Sachin            |1200      |
|102       |Michael           |2000      |
|104       |Malcolm           |3500      |
------------------------------------------
```

**Comment by sfc-gh-yixie** [comment]
@narendra-meenaga yeah sort after select may result in unsorted data. This should work with the latest version of snowpark.
```
df.withColumn('emp_first_name',first_name('emp_name'))\
    .select('emp_id','emp_first_name','salary')\
    .sort(col('salary').asc())\
    .show()
```

**Comment by narendra-meenaga** [comment]
@sfc-gh-yixie  Thank you. Upgraded "snowflake-snowpark-python" to  1.4.0 and the issue is not  reproducible.Hence closing the issue.
