### ISSUE TITLE
SNOW-723442: Python version of 3.8

### ISSUE THREAD

**Issue by kamipatel** [snowflakedb/snowpark-python#651]
## What is the current behavior?
Looks like snowpark needs strictly Python 3.8 version no more no less. I can not use Glue as it does not support 3.8

## What is the desired behavior?
Support 3.8 + versions

**Comment by sfc-gh-achandrasekaran** [comment]
@kamipatel we are working on supporting 3.9+ with an ETA of mid 2023. Stay tuned.

**Comment by kamipatel** [comment]
@sfc-gh-achandrasekaran  Thanks for the clarification. Sounds like an issue using Glue jobs as 3.8 is not supported.
