### ISSUE TITLE
SNOW-727473: Put file at StageArea from Snowpark

### ISSUE THREAD

**Issue by sambati555** [snowflakedb/snowpark-python#656]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Replace with the output of `python --version --version`  3.10.5

2. What operating system and processor architecture are you using?

   Replace with the output of `python -c 'import platform; print(platform.platform())'`  windows

3. What are the component versions in the environment (`pip freeze`)?

   Replace with the output of `python -m pip freeze`

4. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

5. What did you expect to see?

   What should have happened and what happened instead?
   put_result = Session.file.put('file://C:\\Users\\sambati\\Desktop\\MCB_Project\\PrePaid_PROD\\CUSTOMER\\SourceFiles\\PEP_*.csv', '@INTERNALSTAGE_PREPAID_CUSTOMER' )
AttributeError: 'property' object has no attribute 'put'

6. Can you set logging to DEBUG and collect the logs?

   ```
   import logging

   for logger_name in ('snowflake.snowpark', 'snowflake.connector'):
       logger = logging.getLogger(logger_name)
       logger.setLevel(logging.DEBUG)
       ch = logging.StreamHandler()
       ch.setLevel(logging.DEBUG)
       ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
       logger.addHandler(ch)
   ```

**Comment by sfc-gh-aalam** [comment]
could you give us the output for `pip freeze` please

**Comment by sfc-gh-stan** [comment]
Hi @sambati555 , it looks like your are calling `.file.put()` on the `snowflake.snowpark.session.Session` class. You need to create a `Session` object, something like:
```
session = Session.builder.configs(CONNECTION_PARAMETERS).create()
put_result = session.file.put(..., ...)
```
Please refer to https://docs.snowflake.com/en/developer-guide/snowpark/python/creating-session.html#creating-a-session-for-snowpark-python for details.
