### ISSUE TITLE
SNOW-754383: [BUG] Issue for missing analyzer argument in SelectSnowflakePlan API.

### ISSUE THREAD

**Issue by pivv** [snowflakedb/snowpark-python#709]
https://github.com/snowflakedb/snowpark-python/blob/a15df2887eb3a09ec67d95c38fdddc4fd6eceb20/src/snowflake/snowpark/dataframe.py#L1752

In line 1752 and 1783, no analyzer is specified, so error occurs: __init__() missing 1 required keyword-only argument: 'analyzer'.
Please check this issue!

**Comment by sfc-gh-yixie** [comment]
Hi @pivv This is a good catch. Thank you. 
I can find a way to reproduce it. But could you share the code to reproduce the issue? I'm curious how your code hits the problem.

**Comment by pivv** [comment]
Hi @sfc-gh-yixie , thank you for your fast response.
To my best knowledge, this is the simplest code to reproduce the issue, though flatten API is now deprecated.

# Assume that connection_parameters are verified.

from snowflake.snowpark import Session

session = Session.builder.configs(connection_parameters).create()

df = session.create_dataframe([(1, 1),(1, 2),(2, 1),(2, 2),(3, 1),(3, 2)], schema=["a", "b"])
df2 = session.create_dataframe([(1, [1]),(1, [2]),(2, [1]),(2, [2]),(3, [1]),(3, [2])], schema=["a", "blist"])
df2 = df2 \
    .flatten(df2["blist"]) \
    .withColumnRenamed("value", "b") \
    .select("a", "b")

df.intersect(df2).show()
