### ISSUE TITLE
SNOW-756413: snowpark.Session.write_pandas() fails to create a df from a pandas df

### ISSUE THREAD

**Issue by pingboing** [snowflakedb/snowpark-python#715]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

Python 3.8.10 (default, Feb 22 2023, 11:05:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]

2. What operating system and processor architecture are you using?

   macOS-12.6.1-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

aiofiles==22.1.0
aiosqlite==0.18.0
anyio==3.6.2
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asn1crypto==1.5.1
asttokens==2.2.1
attrs==22.2.0
autopep8==2.0.1
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
black==23.1.0
bleach==5.0.1
cachetools==5.2.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.0.0
comm==0.1.2
contourpy==1.0.6
cryptography==36.0.2
cycler==0.11.0
davesci==0.3.2
debugpy==1.6.5
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
filelock==3.9.0
fonttools==4.38.0
fqdn==1.5.1
google-auth==2.16.0
idna==3.4
importlib-metadata==6.0.0
importlib-resources==5.12.0
ipykernel==6.20.1
ipython==8.8.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jaraco.classes==3.2.3
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.1
jupyter-events==0.6.0
jupyter-ydoc==0.2.2
jupyter_client==7.4.8
jupyter_core==5.1.3
jupyter_server==2.0.6
jupyter_server_fileid==0.7.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.6.1
jupyterlab==3.5.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.18.0
keyring==23.13.1
keyrings.google-artifactregistry-auth==1.1.1
kiwisolver==1.4.4
lab==7.2
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
more-itertools==9.0.0
mypy-extensions==1.0.0
nameparser==1.1.2
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.1
nest-asyncio==1.5.6
nicknames==0.1.3
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.1
oscrypto==1.3.0
packaging==23.0
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.0
pexpect==4.8.0
phonenumbers==8.13.6
pickleshare==0.7.5
Pillow==9.4.0
pkgutil_resolve_name==1.3.10
platformdirs==2.6.2
pluggy==1.0.0
prometheus-client==0.15.0
prompt-toolkit==3.0.36
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==6.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.10.0
pycparser==2.21
pycryptodomex==3.16.0
Pygments==2.14.0
PyJWT==2.6.0
pyOpenSSL==21.0.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.7
PyYAML==6.0
pyzmq==24.0.1
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
scikit-learn==1.2.1
scipy==1.10.0
seaborn==0.12.2
Send2Trash==1.8.0
simplejson==3.18.1
six==1.16.0
smart-open==6.3.0
sniffio==1.3.0
snowflake-connector-python==2.7.7
snowflake-snowpark-python==1.1.0
soupsieve==2.3.2.post1
stack-data==0.6.2
terminado==0.17.1
textdistance==4.5.0
threadpoolctl==3.1.0
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
traitlets==5.8.1
txt2tags==3.7
typing_extensions==4.5.0
uri-template==1.2.0
urllib3==1.26.13
wcwidth==0.2.5
webcolors==1.12
webencodings==0.5.1
websocket-client==1.4.2
widgetsnbextension==4.0.5
y-py==0.5.9
ypy-websocket==0.8.2
zipp==3.11.0

4. What did you do?

```
pandas_df = pd.DataFrame([(1, "Steve"), (2, "Bob")], columns=["id", "name"])
snowpark_df = new_session.write_pandas(pandas_df, "write_pandas_table", auto_create_table=True, create_temp_table=True)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[53], line 3
      1 # import pandas as pd
      2 pandas_df = pd.DataFrame([(1, "Steve"), (2, "Bob")], columns=["id", "name"])
----> 3 snowpark_df = new_session.write_pandas(pandas_df, "write_pandas_table", auto_create_table=True, create_temp_table=True)

File ~/.pyenv/versions/py_38_SP/lib/python3.8/site-packages/snowflake/snowpark/session.py:1279, in Session.write_pandas(self, df, table_name, database, schema, chunk_size, compression, on_error, parallel, quote_identifiers, auto_create_table, create_temp_table, overwrite, table_type)
   1273     else:
   1274         location = (
   1275             (database + "." if database else "")
   1276             + (schema + "." if schema else "")
   1277             + (table_name)
   1278         )
-> 1279     success, nchunks, nrows, ci_output = write_pandas(
   1280         self._conn._conn,
   1281         df,
   1282         table_name,
   1283         database=database,
   1284         schema=schema,
   1285         chunk_size=chunk_size,
   1286         compression=compression,
   1287         on_error=on_error,
   1288         parallel=parallel,
   1289         quote_identifiers=quote_identifiers,
   1290         auto_create_table=auto_create_table,
   1291         overwrite=overwrite,
   1292         table_type=table_type,
   1293     )
   1294 except ProgrammingError as pe:
   1295     if pe.msg.endswith("does not exist"):

**TypeError: write_pandas() got an unexpected keyword argument 'overwrite'**

5. What did you expect to see?

   a newly created snowflake table named 'write_pandas_table' read in from pandas_df and a snowpark df named snowpark_df

**Comment by sfc-gh-yixie** [comment]
Hi I think the reason is your environment has an old version (2.7.7) of `snowflake-connector-python`. Could you update it to the latest or `>=2.7.12` as required by snowpark? In snowpark's setup.py, there is  `CONNECTOR_DEPENDENCY_VERSION = ">=2.7.12, <4.0.0"`

**Comment by pingboing** [comment]
@sfc-gh-yixie, I see. thanks for looking into this. I upgraded it to 3.0.1 and it solves the problem. Feel free to close.
