### ISSUE TITLE
SNOW-756964: Have calling stored procedures just return a dataframe

### ISSUE THREAD

**Issue by brian-kalinowski-sonos** [snowflakedb/snowpark-python#719]
## What is the current behavior?
https://github.com/snowflakedb/snowpark-python/blob/main/src/snowflake/snowpark/session.py#L1866

Calling a stored procedure with the `session.call(sproc_name='my_proc', *args)` just returns the first value of the first row in the dataframe? Just seems a little odd why not just return the full dataframe.

## What is the desired behavior?
change `return df.collect()[0][0] ` to `return df.collect()` or maybe just `return df` in the case it has a larger result set

## How would this improve `snowflake-snowpark-python`?
Predictable return values

**Comment by sfc-gh-achandrasekaran** [comment]
@brian-kalinowski-sonos thanks for the feedback. What are you trying to do in your sproc? Snowflake sprocs *may* return a value but do not have to. If you do not explicitly return a value from within one, we return the df[0][0] or null depending on what happens inside it. Are you working on specific scenarios that require a table to be returned from a sproc?

**Comment by brian-kalinowski-sonos** [comment]
Hey! Yeah I have some sprocs that return a table like: `RETURNS TABLE ("COL1" NUMBER(38,0), "COL2" NUMBER(38,0))`
and some logic based on the return columns that run after, but will have issues if they don't gather all the rows from the result. 

Running `proc_result = session.sql(f'CALL {proc}()').collect()` is fine for our use case but it was just something I noticed when trying to use the `session.call()` method.

**Comment by sfc-gh-achandrasekaran** [comment]
Yep, thanks for providing that context. Gathering all the rows from a sproc may have its own issues w.r.t memory consumption so that is something to keep in mind. Regardless, this is something we have been working on and hope to have an update within the next month or two.
