### ISSUE TITLE
SNOW-835767: create_dataframe: None type converting to empty string

### ISSUE THREAD

**Issue by ironScripter** [snowflakedb/snowpark-python#879]
I am having an issue where a None type passed into the create_dataframe function returns as an empty string type.

Example:
```python
from snowflake.snowpark import Session
input_data = [{ "thing1" : {  "subThing1": "Sub thing Value" }, "thing2": None }]
df = Session.create_dataframe(input_data)
print(df.dtypes)
```
Output
```
[('THING1', 'map<string,string>'), ('THING2', 'string')]
```

This is causing issues when attempting to then use that data frame to merge data into an existing table in snowflake when the target type is anything except VARCHAR. This is being used to take data from an API and insert it a Snowflake DB where the target type is OBJECT or VARIANT but the dataframe being returned is string.

**Comment by sfc-gh-aling** [comment]
thanks for reaching out. can you try specifying the schema when calling `create_dataframe` like the following:

```python
from snowflake.snowpark.types import MapType, NullType
from snowflake.snowpark import Session
session = Session.builder.configs(CONNECTION_PARAMETERS).create()
input_data = [{ "thing1" : {  "subThing1": "Sub thing Value" }, "thing2": None }]
schema = StructType([StructField("thing1", MapType()), StructField("thing2", VariantType())])
df = session.create_dataframe(data=input_data, schema=schema)
print(df.dtypes)
```

for `None` value we default it to `StringType`, so you need to specify the schema explicitly here.
