### ISSUE TITLE
SNOW-853533: to_local_iterator doesn't support generating rows as case-insensitive 

### ISSUE THREAD

**Issue by orrdermer1** [snowflakedb/snowpark-python#926]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

 `Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]`

2. What operating system and processor architecture are you using?

`macOS-13.3.1-arm64-arm-64bit`

3. What are the component versions in the environment (`pip freeze`)?

... (Snowpark 1.5.1)

4. What did you do?

```
df.collect(case_sensitive=False)
df.to_local_iterator()  # No such flag
```

5. What did you expect to see?

Support for constructing case-insensitive rows (the underlying function, `self._session._conn.execute` supports the combination of to_iter=True and case_sensitive=False, looks like just an API addition)

6. Can you set logging to DEBUG and collect the logs?

...

**Comment by sfc-gh-aling** [comment]
thanks for reaching out, I think this should be a straight forward  change.
feel free to make a PR for it, we love community contribution!
