### ISSUE TITLE
SNOW-853748: Snowpark 1.5.0 is tagged as latest when 1.5.1 is released.

### ISSUE THREAD

**Issue by nevdelap** [snowflakedb/snowpark-python#929]
# Steps to Repro

1. Go here: https://github.com/snowflakedb/snowpark-python/releases
2. See this:
![image](https://github.com/snowflakedb/snowpark-python/assets/583807/e19d8dca-5301-4e13-bbff-578eeb19434a)

I wonder if that is why it is not in conda-forge? (It is in anaconda.)

**Comment by nevdelap** [comment]
Do you know, when 1.5.1 will likely appear here, roughly? https://repo.anaconda.com/pkgs/snowflake/ Cheers.

**Comment by sfc-gh-aalam** [comment]
@nevdelap tags have been updated. The packages will be rolled out in a week or so into snowflake anaconda repo.

**Comment by nevdelap** [comment]
Thank you!
